export const IMAGES = {
  logo1: require('../assets/images/interiors_in_mumbai_logo.svg').default,
  logo3: require('../assets/images/interiors_in_mumbai_logo.svg').default,
  video: require('../assets/images/video/pic2-2.webp'),
  background2: require('../assets/images/background/bg2.webp'),
  background3: require('../assets/images/background/bg1.webp'),
  bannerbg3: require('../assets/images/banner/bnr3.webp'),
  bannerbg4: require('../assets/images/banner/bnr4.webp'),
  pic1: require('../assets/images/blog/pic1.webp'),
  pic2: require('../assets/images/blog/blog-grid/pic2.webp'),
  pic3: require('../assets/images/blog/blog-grid/pic3.webp'),
  pic4: require('../assets/images/work/work-1/pic-1.webp'),
  pic5: require('../assets/images/work/work-1/pic-2.webp'),
  pic6: require('../assets/images/work/work-1/pic-3.webp'),
  bg2: require('../assets/images/background/bg2.webp'),
  clientBg: require('../assets/images/client-bg.webp'),
  pic7: require('../assets/images/testimonials/pic1.webp'),
  pic8: require('../assets/images/testimonials/pic2.webp'),
  pic9: require('../assets/images/testimonials/pic3.webp'),
  pic10: require('../assets/images/testimonials/pic4.webp'),
  pic11: require('../assets/images/testimonials/pic5.webp'),
  pic12: require('../assets/images/testimonials/pic6.webp'),
  pic13: require('../assets/images/team/pic1.webp'),
  pic14: require('../assets/images/team/pic2.webp'),
  pic15: require('../assets/images/team/pic3.webp'),
  pic16: require('../assets/images/team/pic4.webp'),
  pic17: require('../assets/images/team/pic5.webp'),
  bg1: require('../assets/images/background/bg1.webp'),
  pic2_1: require('../assets/images/pic2-1.webp'),
  pic2_2: require('../assets/images/pic2-2.webp'),
  bg2_1: require('../assets/images/background/bg2-1.webp'),
  progress: require('../assets/images/video/pic2-1.webp'),
  white2: require('../assets/images/interiors_in_mumbai_logo.svg').default,
  footer1: require('../assets/images/blog/recent-blog/pic1.webp'),
  footer2: require('../assets/images/blog/recent-blog/pic2.webp'),
  team1: require('../assets/images/team/pic1.webp'),
  team2: require('../assets/images/team/pic2.webp'),
  team3: require('../assets/images/team/pic3.webp'),
  team4: require('../assets/images/team/pic4.webp'),
  team5: require('../assets/images/team/pic5.webp'),
  team6: require('../assets/images/team/pic6.webp'),
  modal: require('../assets/images/img1.webp'),
  comingsoonIcon: require('../assets/images/logo-icon.webp'),
  bg8: require('../assets/images/bg8.webp'),
  bnr1: require('../assets/images/banner/bnr1.webp'),
  galleryImg1: require('../assets/images/work/work-1/pic-3.webp'),
  galleryImg2: require('../assets/images/work/work-1/pic-4.webp'),

  mumbai2bhk: require('../assets/images/work/mumbai_2bhk.webp'),
  mumbai3bhk: require('../assets/images/work/mumbai_3bhk.webp'),
  portfolioLivingRoom: require('../assets/images/work/portfolio_living_room.webp'),
  before1bhk: require('../assets/images/work/raw_1bhk_edit.webp'),
  after1bhk: require('../assets/images/work/after_1bhk_edit.webp'),

  // Location Banners
  miraRoadBanner: require('../assets/images/banner/mira_road_banner.webp'),
  andheriBanner: require('../assets/images/banner/andheri_banner.webp'),
  bandraBanner: require('../assets/images/banner/bandra_banner.webp'),
  powaiBanner: require('../assets/images/banner/powai_banner.webp'),
  thaneBanner: require('../assets/images/banner/thane_banner.webp'),
  mumbaiKitchen: require('../assets/images/work/mumbai_kitchen.webp'),

  service1: require('../assets/images/services/pic1.webp'),
  service2: require('../assets/images/services/pic2.webp'),
  service3: require('../assets/images/services/pic3.webp'),
  service4: require('../assets/images/services/pic4.webp'),
  service5: require('../assets/images/services/pic5.webp'),
  service6: require('../assets/images/services/pic6.webp'),


  workPic1: require('../assets/images/work/work-1/pic-1.webp'),
  workPic2: require('../assets/images/work/work-1/pic-2.webp'),
  workPic3: require('../assets/images/work/work-1/pic-3.webp'),
  workWorkpic1: require('../assets/images/work/pic1.webp'),
  workWorkpic2: require('../assets/images/work/pic2.webp'),
  bnr6: require('../assets/images/banner/bnr6.webp'),
  brand1: require('../assets/images/logo/logo-gray1.webp'),
  brand2: require('../assets/images/logo/logo-gray2.webp'),
  brand3: require('../assets/images/logo/logo-gray3.webp'),
  brand4: require('../assets/images/logo/logo-gray4.webp'),
  brand5: require('../assets/images/logo/logo-gray5.webp'),
  brand6: require('../assets/images/logo/logo-gray6.webp'),
  bnr5: require('../assets/images/banner/bnr5.webp'),
  ServicesDetailBg2: require('../assets/images/background/bg2.webp'),
  ServicePic1: require('../assets/images/services/service-detail/pic1.webp'),
  ServicePic2: require('../assets/images/services/service-detail/pic2.webp'),
  ServicePic3: require('../assets/images/services/service-detail/pic3.webp'),
  ServicePic4: require('../assets/images/services/service-detail/pic4.webp'),
  ServicePic5: require('../assets/images/services/service-detail/pic5.webp'),
  ServicePic6: require('../assets/images/services/service-detail/pic6.webp'),
  ServicePic7: require('../assets/images/services/service-detail/pic7.webp'),
  ServicePic8: require('../assets/images/services/service-detail/pic8.webp'),
  ServicePic9: require('../assets/images/services/service-detail/pic9.webp'),
  ServicePic10: require('../assets/images/services/service-detail/pic10.webp'),
  ServicePic11: require('../assets/images/services/service-detail/pic11.webp'),
  ServicePic12: require('../assets/images/services/service-detail/pic12.webp'),
  ServicePic13: require('../assets/images/services/service-detail/pic13.webp'),
  ServicePic14: require('../assets/images/services/service-detail/pic14.webp'),
  blogGridPic1: require('../assets/images/blog/large/pic2.webp'),
  blogGridPic2: require('../assets/images/blog/large/pic1.webp'),
  blogGridPic3: require('../assets/images/blog/large/pic3.webp'),
  bnr4: require('../assets/images/banner/bnr4.webp'),
  post1: require('../assets/images/blog/recent-blog/pic1.webp'),
  post2: require('../assets/images/blog/recent-blog/pic2.webp'),
  post3: require('../assets/images/blog/recent-blog/pic3.webp'),
  post4: require('../assets/images/blog/recent-blog/pic4.webp'),
  bnr2: require('../assets/images/banner/bnr2.webp'),
  testimonial: require('../assets/images/testimonials/pic4.webp'),
  avatar: require('../assets/images/testimonials/pic1.webp'),
  avatar1: require('../assets/images/testimonials/pic2.webp'),
  avatar2: require('../assets/images/testimonials/pic3.webp'),
  home2Bg1: require('../assets/images/background/bg1.webp'),
  home2slider1: require('../assets/images/main-slider/side3.webp'),
  home2slider2: require('../assets/images/main-slider/side4.webp'),
  home2slider3: require('../assets/images/main-slider/pic3.webp'),
  home2slider4: require('../assets/images/main-slider/pic4.webp'),
  home2slider5: require('../assets/images/main-slider/pic5.webp'),
  home2about1: require('../assets/images/about/pic4.webp'),
  home2Bg2: require('../assets/images/background/bg2-1.webp'),
  home2sliderImg1: require('../assets/images/work/work-1/pic-1.webp'),
  home2sliderImg2: require('../assets/images/work/work-1/pic-2.webp'),
  home2sliderImg3: require('../assets/images/work/work-1/pic-3.webp'),
  aboutTestimonial: require('../assets/images/about/pic5.webp'),
  home3slider1: require('../assets/images/main-slider/slider3/pic1.webp'),
  home3slider2: require('../assets/images/main-slider/slider3/pic2.webp'),
  home3slider3: require('../assets/images/main-slider/slider3/pic3.webp'),
  home3aboutUs1: require('../assets/images/about/pic6.webp'),
  home3aboutUs2: require('../assets/images/about/pic7.webp'),
  home3aboutpic8: require('../assets/images/about/pic8.webp'),
  home3aboutpic9: require('../assets/images/about/pic9.webp'),
  home3aboutpic10: require('../assets/images/about/pic10.webp'),
  videoPic3: require('../assets/images/video/pic3.webp'),
  home3blogimg1: require('../assets/images/blog/blog-grid/pic4.webp'),
  home3blogimg2: require('../assets/images/blog/latest-blog/pic1.webp'),
  home3blogimg3: require('../assets/images/blog/blog-grid/pic5.webp'),
  home3blogimg4: require('../assets/images/blog/latest-blog/pic2.webp'),
  home3blogimg5: require('../assets/images/blog/blog-grid/pic6.webp'),
  home3blogimg6: require('../assets/images/blog/latest-blog/pic1.webp'),
  footerBgimg: require('../assets/images/footer-bg.webp'),
  footerLogoImg: require('../assets/images/interiors_in_mumbai_logo.svg').default,

  //Switcher Images
  smallbgimg1: require('../assets/images/switcher/small/background/bg1.webp'),
  smallbgimg2: require('../assets/images/switcher/small/background/bg2.webp'),
  smallbgimg3: require('../assets/images/switcher/small/background/bg3.webp'),
  smallbgimg4: require('../assets/images/switcher/small/background/bg4.webp'),
  smallbgimg5: require('../assets/images/switcher/small/background/bg5.webp'),
  smallbgimg6: require('../assets/images/switcher/small/background/bg6.webp'),
  smallbgimg7: require('../assets/images/switcher/small/background/bg7.webp'),
  smallbgimg8: require('../assets/images/switcher/small/background/bg8.webp'),

  smallpattern1: require('../assets/images/switcher/small/pattern/pt1.webp'),
  smallpattern2: require('../assets/images/switcher/small/pattern/pt2.webp'),
  smallpattern3: require('../assets/images/switcher/small/pattern/pt3.webp'),
  smallpattern4: require('../assets/images/switcher/small/pattern/pt4.webp'),
  smallpattern5: require('../assets/images/switcher/small/pattern/pt5.webp'),
  smallpattern6: require('../assets/images/switcher/small/pattern/pt6.webp'),
  smallpattern7: require('../assets/images/switcher/small/pattern/pt7.webp'),
  smallpattern8: require('../assets/images/switcher/small/pattern/pt8.webp'),

  largebgimg1: require('../assets/images/switcher/large/background/bg1.webp'),
  largebgimg2: require('../assets/images/switcher/large/background/bg2.webp'),
  largebgimg3: require('../assets/images/switcher/large/background/bg3.webp'),
  largebgimg4: require('../assets/images/switcher/large/background/bg4.webp'),
  largebgimg5: require('../assets/images/switcher/large/background/bg5.webp'),
  largebgimg6: require('../assets/images/switcher/large/background/bg6.webp'),
  largebgimg7: require('../assets/images/switcher/large/background/bg7.webp'),
  largebgimg8: require('../assets/images/switcher/large/background/bg8.webp'),

  largepattern1: require('../assets/images/switcher/large/pattern/pt1.webp'),
  largepattern2: require('../assets/images/switcher/large/pattern/pt2.webp'),
  largepattern3: require('../assets/images/switcher/large/pattern/pt3.webp'),
  largepattern4: require('../assets/images/switcher/large/pattern/pt4.webp'),
  largepattern5: require('../assets/images/switcher/large/pattern/pt5.webp'),
  largepattern6: require('../assets/images/switcher/large/pattern/pt6.webp'),
  largepattern7: require('../assets/images/switcher/large/pattern/pt7.webp'),
  largepattern8: require('../assets/images/switcher/large/pattern/pt8.webp'),

}

const appTheme = {
  IMAGES
}

export default appTheme;
